### ISSUE TITLE
iotop failed with ValueError on ubuntu

### ISSUE THREAD

**Issue by Graha** [Graha/iotop#1]
Traceback (most recent call last):
  File "iotop.py", line 12, in <module>
    main()
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 620, in main
    main_loop()
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 610, in <lambda>
    main_loop = lambda: run_iotop(options)
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 508, in run_iotop
    return curses.wrapper(run_iotop_window, options)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 501, in run_iotop_window
    ui.run()
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 155, in run
    self.process_list.duration)
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 434, in refresh_display
    lines = self.get_data()
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 415, in get_data
    return list(map(format, processes))
  File "/home/phoenix/graha/iotop-0.6/iotop/ui.py", line 388, in format
    cmdline = p.get_cmdline()
  File "/home/phoenix/graha/iotop-0.6/iotop/data.py", line 292, in get_cmdline
    proc_status = parse_proc_pid_status(self.pid)
  File "/home/phoenix/graha/iotop-0.6/iotop/data.py", line 196, in parse_proc_pid_status
    key, value = line.split(':\t', 1)
ValueError: need more than 1 value to unpack

**Comment by Graha** [comment]
Fixed and code in master branch... Reference Checkin 7c51ce0e29bd135c216f18e18f0c4ab769af0d6f
